# PvPToggle by Majekdor | Created 06/07/2020 | Updated 11/26/2020
# Need help? Message me on Discord @Majekdor#6346

# Set whether pvp is on by default (default: false)
default-pvp: false

# Set whether pvp is automatically set to false on join
off-on-join: false

# If true, only players with permission pvptoggle.use can use /pvp (default: false)
use-permissions: false

# Set a cooldown for the time between players using /pvp
# Default: -1 (no cooldown) put number in seconds if you change this
pvp-cooldown: -1

# Set whether or not changes in PvP status are logged to console (default: false)
console-log: false

# Don't set to true unless you want players to see random messages or other undesirable behavior
debug: false

# Database settings for MySQL support
# Only enable this if you know what you're doing and have an existing database
# If database is disabled the plugin will use SQLite for data storage
database-enabled: false
host: ''
port: ''
database: ''
username: ''
password: ''
use-ssl: false

# =========================
# | MESSAGE CONFIGURATION |
# =========================
# Feel free to use any mc color code
# %player% is replaced with the relevant player name
# If %player% isn't in a message, don't put it there. It won't work
pvp-enabled: '&6PvP is now: &aEnabled'

pvp-disabled: '&6PvP is now: &cDisabled'

no-pvp: '&6PvP is disabled. Use &7/pvp &6to turn it on.'

other-pvp: '&b%player% &6has PvP disabled!'

unknown-player: '&cUnable to locate player %player%.'

no-permission: '&cYou do not have permission to do that!'

unknown-command: '&cUnknown command. &7Usage: /pvp <on|off> [player]'

# The below messages use the strings at the bottom of this file

# %toggle% will be replaced with either on or off
# %player% will be replaced with the player who's pvp has been toggled
pvp-toggle-other: '&6PvP is now %toggle% for &b%player%&6.'

# %noun% will be replaced with either you-are or player-is
# %toggle% is either on or off
region-deny: '&c%noun% in a region with PvP forced %toggle%.'

# %toggle% is either on or off
region-enter: '&cYou have entered a region where PvP is forced %toggle%.'

# Strings for placeholders in above messages
forced-on: 'on'
forced-off: 'off'
you-are: 'You are'
player-is: '%player% is'
